window.veilDialogueData = {
  start: "quartier_01",
  mainOrder: [
    "quartier_01", "vue_02", "faim_03", "mere_04", "pere_05", "mort_mere_06",
    "nuit_seul_07", "premier_vol_08", "mafia_09", "organisation_10",
    "membres_11", "salaire_12", "arme_13", "violence_14", "loyaute_15",
    "mallette_16", "helico_17", "deguisement_18", "vip_19", "mallette_20",
    "balle_21", "ufssa_22", "agent_23", "dossiers_24", "cibles_25",
    "argent_26", "peur_27", "regrets_28", "fuite_29", "apres_30"
  ],
  nodes: [
    ["quartier_01", "suspicious", "Tu as déjà vécu dans un endroit où les ascenseurs tombaient plus souvent en panne que les lampes ?", ["Non, mais ça devait être difficile.", 2], ["Tu vivais vraiment dans un gratte-ciel ?", 0], ["Tu exagères peut-être un peu.", -2]],
    ["vue_02", "tired", "De là-haut, toute la ville semblait riche. Sauf notre étage. Tu crois que la vue change quelque chose à la vie ?", ["Non, une belle vue ne nourrit personne.", 2], ["Elle peut au moins donner de l'espoir.", 1], ["Tu aurais préféré vivre ailleurs ?", 0]],
    ["faim_03", "sad", "Quand j'étais petit, je savais reconnaître les jours où il ne fallait pas demander à manger. Tu aurais fait quoi à ma place ?", ["J'aurais essayé d'aider ma famille.", 2], ["Je ne sais pas, j'étais peut-être trop jeune.", 1], ["J'aurais volé de quoi manger.", 0]],
    ["mere_04", "sad", "Ma mère disait toujours que tout irait mieux le mois suivant. Tu penses qu'elle y croyait vraiment ?", ["Elle voulait sûrement te protéger.", 2], ["Peut-être qu'elle essayait de s'en convaincre.", 1], ["Elle te mentait probablement.", -2]],
    ["pere_05", "suspicious", "Je me souviens à peine de mon père. C'est mieux de ne rien savoir ou de connaître une vérité qui fait mal ?", ["La vérité finit toujours par compter.", 1], ["Parfois, ne pas savoir protège.", 1], ["Tu devrais essayer de le retrouver.", -1]],
    ["mort_mere_06", "sad", "Le jour où elle est morte, personne ne m'a demandé si j'avais un endroit où dormir. Ça te surprend ?", ["Oui. Quelqu'un aurait dû t'aider.", 2], ["Malheureusement, pas vraiment.", 0], ["Comment as-tu survécu après ça ?", 1]],
    ["nuit_seul_07", "tired", "La première nuit seul, j'ai dormi dans la cage d'escalier. Tu crois qu'un enfant peut devenir adulte en une seule nuit ?", ["Oui, quand il n'a pas le choix.", 2], ["Non, mais il peut perdre son enfance.", 2], ["Tu avais quel âge exactement ?", 0]],
    ["premier_vol_08", "amused", "La première chose que j'ai volée, c'était un sandwich. Tu appelles ça un crime ?", ["Techniquement oui, moralement non.", 1], ["Tu n'avais probablement pas le choix.", 2], ["Voler reste voler.", -1]],
    ["mafia_09", "neutral", "Un homme m'a vu voler. Au lieu d'appeler la police, il m'a acheté un repas. Tu lui aurais fait confiance ?", ["Pas immédiatement, mais je l'aurais écouté.", 1], ["Oui, il venait de t'aider.", 0], ["Non, personne n'aide gratuitement.", -1]],
    ["organisation_10", "suspicious", "Ils m'ont proposé du travail. Transporter des enveloppes, surveiller des portes, ne poser aucune question. Tu aurais accepté ?", ["Pour survivre, probablement.", 2], ["J'aurais cherché une autre solution.", 0], ["Ça dépend de ce qu'il y avait dans les enveloppes.", 1]],
    ["membres_11", "neutral", "Tu imagines sûrement des monstres. Pourtant, certains étaient plus présents que ma propre famille. Ça change ton jugement ?", ["Oui, les gens sont plus compliqués qu'ils en ont l'air.", 2], ["Un criminel peut quand même faire preuve de bonté.", 1], ["Non, leurs crimes restent leurs crimes.", -1]],
    ["salaire_12", "confident", "Mon premier vrai salaire a payé le loyer de trois familles de l'immeuble. C'était de l'argent sale. Tu l'aurais refusé ?", ["Non, si des familles en avaient besoin.", 1], ["J'aurais hésité.", 0], ["Oui, l'origine de l'argent compte.", -1]],
    ["arme_13", "tired", "La première fois qu'on m'a donné une arme, j'ai eu peur de la tenir. Tu pensais que ça me ferait plaisir ?", ["Non, tu étais encore très jeune.", 2], ["Peut-être que tu voulais te sentir puissant.", -1], ["Quand as-tu cessé d'avoir peur ?", 0]],
    ["violence_14", "suspicious", "Un homme devait être puni. On m'a demandé de surveiller la porte pendant qu'ils s'en occupaient. Est-ce que ça faisait déjà de moi un complice ?", ["Oui, même sans entrer dans la pièce.", -1], ["Tu étais manipulé.", 2], ["Tout dépend de ce que tu savais.", 0]],
    ["loyaute_15", "confident", "Ils m'ont sauvé quand personne d'autre ne l'a fait. Tu comprends pourquoi je leur étais loyal ?", ["Oui, même si leurs méthodes étaient mauvaises.", 2], ["Je comprends, mais tu leur devais vraiment toute ta vie ?", 1], ["Non, la gratitude ne justifie pas tout.", -1]],
    ["mallette_16", "neutral", "La mallette contenait les plans d'une arme. On nous avait dit qu'elle empêcherait une guerre. Tu aurais posé davantage de questions ?", ["Oui, surtout pour quelque chose d'aussi dangereux.", 1], ["Dans l'urgence, peut-être pas.", 0], ["Qui vous avait donné cette information ?", 1]],
    ["helico_17", "amused", "J'aimais les arrivées en hélicoptère. Ça donnait l'impression qu'on contrôlait tout. Pourquoi les pires erreurs commencent-elles souvent comme ça ?", ["Parce que la confiance rend imprudent.", 1], ["Parce que quelqu'un vous manipulait.", 1], ["Tu étais trop sûr de toi.", -1]],
    ["deguisement_18", "neutral", "J'ai pris l'uniforme d'un garde pour entrer. C'est étrange de voir à quel point les gens respectent un vêtement, non ?", ["Les gens voient souvent l'uniforme avant la personne.", 1], ["Tu avais peur d'être reconnu ?", 0], ["C'était plutôt intelligent.", 1]],
    ["vip_19", "suspicious", "Il suffisait d'un costume plus cher pour que tout le monde ouvre les portes. Tu crois vraiment que le pouvoir ressemble à ça ?", ["Souvent, le pouvoir repose sur l'apparence.", 1], ["Le vrai pouvoir, c'est de connaître les bonnes personnes.", 0], ["Tu sembles encore en vouloir à ce VIP.", -1]],
    ["mallette_20", "tired", "Quand j'ai enfin pris la mallette, je n'ai rien ressenti. Ni victoire, ni peur. Ça t'est déjà arrivé de poursuivre quelque chose qui ne comptait plus une fois obtenu ?", ["Oui, l'objectif peut perdre son sens.", 2], ["Peut-être que tu sentais déjà le piège.", 1], ["Tu aurais dû l'abandonner.", -1]],
    ["balle_21", "angry", "La balle dans ma jambe était un traceur. J'ai survécu, mais elle les a conduits jusqu'à moi. Tu appelles ça de la chance ?", ["Une chance empoisonnée.", 1], ["Non, ils avaient tout prévu.", 1], ["Tu aurais dû faire examiner la balle.", -1]],
    ["ufssa_22", "angry", "Ils sont entrés chez moi sans frapper et m'ont proposé la prison ou le travail. Ça ressemble à un choix pour toi ?", ["Non, c'était une menace.", 2], ["Tu pouvais peut-être encore refuser.", -2], ["Ils savaient que tu accepterais.", 0]],
    ["agent_23", "tired", "Ils m'appelaient agent, mais je savais que j'étais un prisonnier avec une arme. Quelle différence vois-tu entre les deux ?", ["Un agent peut dire non.", 2], ["Un prisonnier sait au moins qu'il est enfermé.", 1], ["Dans ton cas, aucune.", 0]],
    ["dossiers_24", "suspicious", "Chaque dossier présentait une cible comme un monstre. Puis je découvrais les pages qu'ils avaient retirées. Tu aurais continué les missions ?", ["Seulement le temps de comprendre leur plan.", 1], ["Non, j'aurais cherché à fuir immédiatement.", 1], ["Ça dépendait des crimes réels de la cible.", 0]],
    ["cibles_25", "sad", "Certaines cibles étaient coupables. D'autres dérangeaient seulement la mauvaise personne. Est-ce que cette différence efface ce que j'ai fait ?", ["Non, mais elle explique pourquoi tu as changé.", 2], ["Tu ne pouvais pas toujours connaître la vérité.", 1], ["Rien ne peut effacer certaines actions.", -1]],
    ["argent_26", "neutral", "J'ai commencé à cacher de l'argent pour préparer ma fuite. Tu appelles ça de la prudence ou une nouvelle trahison ?", ["De la prudence. Ils t'utilisaient.", 2], ["Les deux à la fois.", 0], ["Tu pensais seulement à toi.", -1]],
    ["peur_27", "tired", "Chaque fois qu'un agent me saluait, je me demandais s'il savait déjà. Tu crois qu'on peut vivre longtemps comme ça ?", ["Non, la peur finit par épuiser.", 2], ["Oui, si on sait très bien mentir.", 0], ["Tu aurais dû partir plus tôt.", -1]],
    ["regrets_28", "sad", "Je ne regrette pas d'avoir survécu. Je regrette ce que j'ai dû devenir. Tu vois la différence ?", ["Oui, survivre n'oblige pas à aimer ce qu'on est devenu.", 2], ["Je la comprends, mais tes choix restent les tiens.", 0], ["Tu cherches surtout à te pardonner.", -1]],
    ["fuite_29", "confident", "Un jour, je quitterai leur siège avec leur argent, leurs dossiers et une nouvelle identité. Tu crois que je mérite de réussir ?", ["Oui, si tu exposes aussi la vérité.", 2], ["Tu mérites surtout une chance de changer.", 2], ["Pas si tu abandonnes les victimes derrière toi.", -1]],
    ["apres_30", "tired", "Si j'arrive dans un autre pays avec de l'argent, une villa et des gardes, est-ce que je serai enfin libre ?", ["Non, pas tant que ton passé te poursuit.", 1], ["Peut-être, si tu construis une autre vie.", 2], ["Tu risques seulement de créer une nouvelle prison.", 1]]
  ].map((item, index, all) => ({
    id: item[0],
    expression: item[1],
    characterText: item[2],
    minTrust: 0,
    choices: item.slice(3).map((choice) => ({
      text: choice[0],
      trustChange: choice[1],
      next: all[index + 1]?.[0] || "infinite"
    }))
  })),
  secondary: [
    "Je gardais toujours un billet plié dans ma chaussure. Pas par paranoïa. Par expérience.",
    "La soupe de l'immeuble avait le goût de métal. On la mangeait quand même.",
    "Il y avait un voisin qui réparait les portes avec du fil électrique. Il appelait ça de l'art.",
    "Ma mère chantait quand elle avait peur. Je ne l'ai compris que trop tard.",
    "Un jour, j'ai surveillé une enveloppe pendant six heures. Je n'ai jamais su ce qu'il y avait dedans.",
    "La mafia m'a appris à mentir. La UFSSA m'a appris à le faire avec un badge.",
    "Je n'aime pas les costumes. Ils transforment les gens en symboles.",
    "La faim ne rend pas noble. Elle rend précis.",
    "J'ai perdu des amis parce qu'ils étaient loyaux envers les mauvaises personnes.",
    "Un homme de l'organisation m'a offert des chaussures neuves. Il a disparu deux semaines après.",
    "Je connais mieux les sorties de secours que les entrées principales.",
    "La musique forte couvre les sirènes. C'est pour ça que j'en mettais souvent.",
    "Je pensais vouloir de l'argent. Maintenant je crois que je veux surtout un endroit où personne ne me connaît.",
    "Avant chaque mission, je vérifie mes mains. Si elles tremblent, je respire jusqu'à ce qu'elles mentent.",
    "Les déguisements ne changent pas qui tu es. Ils changent seulement ce que les autres osent voir.",
    "Tu sais ce qui est drôle ? Les gens font plus confiance à une cravate qu'à un visage.",
    "Je n'ai jamais aimé les ascenseurs. Trop lents. Trop faciles à bloquer.",
    "La UFSSA archive tout. Même les mensonges ont un numéro de dossier.",
    "J'ai parfois envie d'appeler quelqu'un de mon ancien quartier. Puis je me rappelle que ça les mettrait en danger.",
    "Je dors dos au mur. Vieille habitude.",
    "Le dernier souvenir précis de ma mère ? Ses mains froides autour d'une tasse vide.",
    "Mon ancien patron ne m'a pas seulement protégé. Il m'a construit comme un outil.",
    "Le vrai plan après ma fuite ? Changer de nom avant de changer de pays.",
    "Je ne sais plus si je veux être riche ou invisible.",
    "J'ai plus peur du silence après une mission que de la mission elle-même.",
    "Il y avait un enfant au 41e étage qui dessinait des plages. Il n'avait jamais vu la mer.",
    "Certains repas volés avaient meilleur goût que les banquets de la mafia.",
    "Je n'ai jamais su dire merci correctement. Ça ressemblait trop à une dette.",
    "Les gardes regardent les mains. Les civils regardent les yeux.",
    "Quand quelqu'un dit que tout ira bien, je cherche la sortie.",
    "La pauvreté te donne une mémoire bizarre. Tu oublies les dates, pas les odeurs.",
    "Je juge les pièces par leurs fenêtres.",
    "Un bon mensonge doit être assez petit pour tenir dans une poche.",
    "Je n'ai pas peur de mourir. J'ai peur qu'on écrive ma version à ma place.",
    "Tu aurais fait quoi, toi, si survivre voulait dire devenir utile à des monstres ?",
    "On me demande souvent si je regrette. Jamais si j'ai eu le temps de choisir.",
    "Les uniformes sont des raccourcis. Les gens adorent les raccourcis.",
    "Une villa ne m'impressionne pas. Une porte qui ferme correctement, déjà plus.",
    "Je garde toujours une fausse identité prête. Même quand je dors.",
    "Si tu veux une confession, il faudra mieux faire qu'un regard triste."
  ]
};
